services:
  - type: web
    name: ai-prescription-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
