# Generated by Django 5.2.3 on 2025-07-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0002_alter_userprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='users.userprofile', verbose_name='doctor'),
            preserve_default=False,
        ),
    ]
