# Generated by Django 5.2.3 on 2025-07-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_doctor'),
        ('users', '0002_alter_userprofile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='users.userprofile', verbose_name='doctor'),
        ),
    ]
