# Generated by Django 5.2.3 on 2025-06-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Nephrology', 'Nephrology'), ('Pulmonology', 'Pulmonology'), ('Rheumatology', 'Rheumatology'), ('Infectious Disease', 'Infectious Disease'), ('Hematology', 'Hematology'), ('Oncology', 'Oncology'), ('Geriatrics', 'Geriatrics'), ('Neurology', 'Neurology'), ('Psychiatry', 'Psychiatry'), ('Pediatrics', 'Pediatrics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('Urology', 'Urology'), ('Ophthalmology', 'Ophthalmology'), ('Otolaryngology (ENT)', 'Otolaryngology (ENT)'), ('Family Medicine', 'Family Medicine'), ('Emergency Medicine', 'Emergency Medicine')], default='General Medicine', max_length=100),
        ),
    ]
